name: Ping Search Engines
on:
  push:
    branches: [main]
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Google
        run: curl "https://www.google.com/ping?sitemap=https://puneet.is-a.dev/sitemap.xml"
      - name: Ping Bing
        run: curl "https://www.bing.com/ping?sitemap=https://puneet.is-a.dev/sitemap.xml"